"""
Web UI for the Google Places lead finder.

Local run:
    export GOOGLE_MAPS_API_KEY=your-key-here
    python3 app.py
    open http://localhost:5001

Hosted (Render): see README.md. Render sets PORT for you and the app
reads GOOGLE_MAPS_API_KEY from the environment variable you configure
in the Render dashboard — no code changes needed between local and
hosted.
"""

import csv
import json
import os
import threading
import time
import uuid

from flask import Flask, jsonify, render_template, request, send_from_directory

from worker import run_job

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
JOBS_DIR = os.path.join(BASE_DIR, "jobs")
os.makedirs(JOBS_DIR, exist_ok=True)

app = Flask(__name__)


def job_dir_for(job_id):
    # job_id is generated by this app (timestamp + uuid hex), never taken
    # verbatim from user input, so it's safe to join onto the filesystem path.
    path = os.path.join(JOBS_DIR, job_id)
    if not os.path.isdir(path):
        return None
    return path


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/jobs", methods=["POST"])
def create_job():
    payload = request.get_json(force=True)

    search_term = (payload.get("search_term") or "").strip()
    raw_locations = payload.get("locations") or ""
    locations = [line.strip() for line in raw_locations.splitlines() if line.strip()]

    if not search_term:
        return jsonify({"error": "Business type / search term is required."}), 400
    if not locations:
        return jsonify({"error": "At least one zip code or city is required."}), 400

    try:
        min_reviews = int(payload.get("min_reviews") or 0)
    except (TypeError, ValueError):
        min_reviews = 0

    try:
        radius_miles = float(payload.get("radius_miles") or 15)
    except (TypeError, ValueError):
        radius_miles = 15
    radius_meters = max(1000, min(radius_miles * 1609.34, 50000))  # Google caps at 50km

    website_filter = payload.get("website_filter") or "any"
    if website_filter not in ("any", "no_website", "has_website"):
        website_filter = "any"

    if not os.environ.get("GOOGLE_MAPS_API_KEY"):
        return jsonify({
            "error": "GOOGLE_MAPS_API_KEY is not set on the server. "
                     "See README.md for how to create and configure one."
        }), 400

    job_id = time.strftime("%Y%m%d-%H%M%S-") + uuid.uuid4().hex[:6]
    job_dir = os.path.join(JOBS_DIR, job_id)
    os.makedirs(job_dir, exist_ok=True)

    job_config = {
        "search_term": search_term,
        "locations": locations,
        "min_reviews": min_reviews,
        "website_filter": website_filter,
        "radius_meters": radius_meters,
    }
    with open(os.path.join(job_dir, "job.json"), "w") as f:
        json.dump(job_config, f, indent=2)

    thread = threading.Thread(target=run_job, args=(job_dir,), daemon=True)
    thread.start()

    return jsonify({"job_id": job_id})


@app.route("/api/jobs/<job_id>/status")
def job_status(job_id):
    jdir = job_dir_for(job_id)
    if not jdir:
        return jsonify({"error": "unknown job"}), 404

    status_path = os.path.join(jdir, "status.json")
    if not os.path.exists(status_path):
        return jsonify({"phase": "starting", "message": "Starting up..."})

    with open(status_path) as f:
        try:
            status = json.load(f)
        except json.JSONDecodeError:
            status = {"phase": "starting", "message": "Starting up..."}

    status["files"] = [
        name for name in ("leads.csv", "leads_filtered.csv")
        if os.path.exists(os.path.join(jdir, name))
    ]
    return jsonify(status)


@app.route("/api/jobs/<job_id>/preview")
def job_preview(job_id):
    jdir = job_dir_for(job_id)
    if not jdir:
        return jsonify({"error": "unknown job"}), 404

    filtered_path = os.path.join(jdir, "leads_filtered.csv")
    if not os.path.exists(filtered_path):
        return jsonify({"rows": []})

    with open(filtered_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    rows = rows[-100:]
    rows.reverse()
    return jsonify({"rows": rows})


@app.route("/api/jobs/<job_id>/download/<filename>")
def job_download(job_id, filename):
    jdir = job_dir_for(job_id)
    if not jdir:
        return jsonify({"error": "unknown job"}), 404
    if filename not in ("leads.csv", "leads_filtered.csv"):
        return jsonify({"error": "not allowed"}), 400
    if not os.path.exists(os.path.join(jdir, filename)):
        return jsonify({"error": "not ready yet"}), 404
    return send_from_directory(jdir, filename, as_attachment=True)


@app.route("/api/jobs/<job_id>/stop", methods=["POST"])
def job_stop(job_id):
    jdir = job_dir_for(job_id)
    if not jdir:
        return jsonify({"error": "unknown job"}), 404
    with open(os.path.join(jdir, "stop.flag"), "w") as f:
        f.write("stop")
    return jsonify({"ok": True})


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5001))
    app.run(host="0.0.0.0", port=port, debug=False)
